[package]
name = "rust-anpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.5.5"
nalgebra = "0.30.1"
approx = "0.5.1"
